<a href="https://colab.research.google.com/github/danielgetahun100/CMSC204/blob/master/mit%20deeplearning%20save%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import tensorflow as tf

# Download and import the MIT Introduction to Deep Learning package
!pip install mitdeeplearning --quiet
import mitdeeplearning as mdl

import numpy as np
import matplotlib.pyplot as plt

#import relevant packages
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

matrix= tf.constant([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],tf.float32)
print("'bull' has rank {} ".format(tf.rank(matrix)))

shit=tf.zeros([10,256,256,3])

assert tf.rank(shit).numpy()==4, "Matrix must be of rank 4"
print("Rank is {} ".format(tf.shape(shit).numpy()))

row_vector= matrix[0]
column_vector=matrix[:,1]
scalar=matrix[2,2]

print("'row vector': {}".format(row_vector.numpy()))
print("'column_vector': {}".format(column_vector.numpy()))
print("'scalar': {}".format(scalar.numpy()))


a1=tf.constant(15)
b1=tf.constant(61)

c1=tf.add(a1,b1)
c2=a1+b1

print(c1)
print(c2)

#Defining tensor computaion

def func(a,b):
  c=tf.add(a,b)
  d=tf.subtract(b,1)
  e=tf.multiply(c,d)

  return e

#Example computaion
a,b=1.5, 2.5
e_out=func(a,b)
print(e_out)

##defining a network layer

class OurDenseLayer(tf.keras.layers.Layer):
    def __init__(self, n_output_nodes):
      super(OurDenseLayer, self).__init__()
      self.n_output_nodes = n_output_nodes

    def build(self,input_shape):
      d=int(input_shape[-1])

      self.W=self.add_weight(name="weight", shape=[d, self.n_output_nodes])
      self.b= self.add_weight(name="bias", shape=[1, self.n_output_nodes])
    def call(self, x):
      z=tf.matmul(x,self.W)+self.b

      y=tf.sigmoid(z)

      return y

tf.keras.utils.set_random_seed(1)
layer = OurDenseLayer(3)
layer.build((1,2))
x_input = tf.constant([[1,2.]], shape=(1,2))
y= layer.call(x_input)

print(y.numpy())
mdl.lab1.test_custom_dense_layer_output(y)

##sequential model


n_output_nodes= 3

model = Sequential()

dense_layer=Dense(n_output_nodes,activation="sigmoid",use_bias=True,input_shape=(2,))

model.add(dense_layer)





#Test model with example input

x_input = tf.constant([[1,2.]], shape=(1,2))

'''TODO: feed input into the model and predict the output!'''
model_output = model(x_input)
print(model_output)










'bull' has rank 2 
Rank is [ 10 256 256   3] 
'row vector': [1. 2. 3.]
'column_vector': [2. 5. 8.]
'scalar': 9.0
tf.Tensor(76, shape=(), dtype=int32)
tf.Tensor(76, shape=(), dtype=int32)
tf.Tensor(6.0, shape=(), dtype=float32)
[[0.27064407 0.18269512 0.50374055]]
[PASS] test_custom_dense_layer_output
tf.Tensor([[0.18752207 0.23909676 0.3213029 ]], shape=(1, 3), dtype=float32)
Rando:  tf.Tensor([0.16513085 0.9014813  0.6309742 ], shape=(3,), dtype=float32)
